Update backend.yml

diff --git a/.github/workflows/backend.yml b/.github/workflows/backend.yml
--- a/.github/workflows/backend.yml
+++ b/.github/workflows/backend.yml
@@ -11,30 +11,30 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+    - uses: actions/checkout@v4
+    - name: Set up Docker Compose
+      run: docker-compose up -d
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v2
+    - name: Wait for the backend to be ready
+      run: sleep 60
 
-    - name: Install Docker Compose
+    - name: Test the FastAPI app
       run: |
-        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-        sudo chmod +x /usr/local/bin/docker-compose
-        docker-compose --version
+        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:15564/ping)
+        echo "Response code: $RESPONSE"
+        if [ "$RESPONSE" == "200" ]; then 
+          echo "Ping test passed";
+        else
+          echo "Ping test failed";
+          exit 1;
+        fi
+    - name: Get backend service logs
+      if: failure()
+      run: docker-compose logs backend
+    - name: Get db service logs
+      if: failure()
+      run: docker-compose logs db
+    - name: Stop and remove Docker Compose services
+      run: docker-compose down
 
-    - name: Build and run Docker Compose
-      run: |
-        cd CompUGE-Backend
-        docker-compose up -d
-        # Wait for backend service to be up
-        sleep 15
-        # Check if backend service is reachable
-        curl -f http://localhost:15564 || exit 1
-
-    - name: Shut down Docker Compose
-      run: |
-        cd CompUGE-Backend
-        docker-compose down
